import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import ToggleNavContext from "@/components/context/ToggleNavContext";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const poppins = Poppins({
	weight: ["400", "500", "600", "700"],
	subsets: ["latin"],
});

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<ToggleNavContext>
				<body className={poppins.className + " bg-gray-bg"}>{children}</body>
			</ToggleNavContext>
		</html>
	);
}
